# Default values for casa-close-settlement-window.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: casablanca-casa-docker-release.jfrog.io/casa-close-settlement-window
  tag: latest
  pullPolicy: Always
  imagePullSecrets:
  - name: dock-casa-secret

# Example file.
# "1" and "2" are the participantId values from the db.
# "name" and "accountId" values will go into the settlement file and therefore should correspond to
# the ("real money") settlement bank account.
# The settlement file is in ISO 20022 pain.001.001.03 format, the country should therefore be the
# appropriate ISO 3166 Alpha 2 code. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2.
# {
#     "1": {
#         "name": "DFSP1",
#         "country": "CI",
#         "accountId": "1234567890"
#     },
#     "2": {
#         "name": "DFSP2",
#         "country": "CI",
#         "accountId": "5678"
#     }
# }
dfspConfFile: dfspconf.json

# Midnight every day. Uses cron job format. See https://en.wikipedia.org/wiki/Cron#CRON_expression.
schedule: "0 0 * * *"
# It's best for minWindowAgeMs to be as close as possible to the interval between window closures.
# This is because the first thing the scheduled closure job does is close a window. Therefore, if a
# failure occurs later in the process, causing the job to be retried, we won't end up with a number
# of window closures. Maximising minWindowAgeMs gives an operator the maximum amount of time to
# handle failure as required. "Why retry the job?" you ask- job failure can be caused by a range of
# transient conditions, including database outages, orchestrator scheduling errors, network
# connection errors. It's better to be resilient to these and avoid manually processing window
# closures.
# 23 hours and 48 minutes:
# 23.8 * 60 * 60 * 1000 = 85680000
minWindowAgeMs: "85680000"
settlementsEndpoint: "http://casa-centralsettlement:3007/v1/"
operatorSettlementsEndpoint: "http://operator-settlement-test"
centralLedgerAdminEndpoint: "http://centralledger-service:3001"
