apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
      app: {{ .Chart.Name }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
type: Opaque
data:
  DFSP_CONF: {{ required "A valid DFSP config file is required" (.Files.Get .Values.dfspConfFile) | b64enc }}
