image:
  repository: casablanca-casa-docker-release.jfrog.io/casa-settlement-management
  tag: v10.7.1
  pullPolicy: Always
  imagePullSecrets:
    name: dock-casa-secret

init:
  image:
    name: init
    repository: casablanca-casa-docker-release.jfrog.io/casa-settlement-management-init
    tag: 10.7.1
    pullPolicy: Always

db:
  protocol: 'mysql'
  host: '$release_name-centralledger-mysql'
  port: '3306'
  user: 'central_ledger'
  password: 'oyMxgZChuu'
  schema: 'central_ledger'

service:
  type: ClusterIP
  port: 5000

config:
  CENTRAL_LEDGER_SERVICE_NAME: 'centralledger-service'
  CENTRAL_LEDGER_SERVICE_ADMIN_PORT: '3001'
  SETTLEMENTS_SERVICE_NAME: 'centralsettlement'
  SETTLEMENTS_SERVICE_PORT: '3007'
  MIN_WINDOW_AGE_MS: '5000'
  OPERATOR_SETTLEMENTS_SERVICE_NAME: 'operator-settlement'
  OPERATOR_SETTLEMENTS_SERVICE_PORT: '80'
