{{- $dbHost := (.Values.db.host | replace "$release_name" .Release.Name) }}
{{- $dbURL := printf "%s://%s:%s@%s:%s/%s" .Values.db.protocol .Values.db.user .Values.db.password $dbHost .Values.db.port .Values.db.schema -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "casa-settlement-management.fullname" . }}
  labels:
      app: {{ template "casa-settlement-management.fullname" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
type: Opaque
data:
  CLEDG_DATABASE_URI: {{ $dbURL | b64enc }}
  DB_PROTOCOL: {{ .Values.db.protocol | b64enc }}
  DB_PASSWORD: {{ .Values.db.password | b64enc }}
